# Site
name: "Anupam Basu"
baseurl: ''
email: 'prime.lens@gmail.com'
# description: 'Data Science, Data Visualization, Machine Learining and more'
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-figure
  
authors:
  anupam:
      name:           Anupam Basu
      site:           ''
      avatar:         /assets/images/avatar1.jpg
      bio:            ''
      email:          prime.lens@gmail.com
      twitter:        https://twitter.com/abasu_

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Anupam
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 5



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
